name: docker-ansible-pr-build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 10
      matrix:
        TAG_NAME: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, rockylinux-8, centos-7, debian-bullseye, debian-buster]

    steps:
    - uses: actions/checkout@v2

    # - name: Install Grype for Vulnerability Scanning of Docker images.
    #   run: |
    #     curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build docker image tag ${{ matrix.TAG_NAME }}
      uses: docker/build-push-action@v2
      with:
        file: ${{matrix.TAG_NAME}}/Dockerfile
        pull: true
        push: false
        tags: darkwizard242/ansible:${{ matrix.TAG_NAME }}

    # - name: Run Grype for Vulnerability Scanning of image
    #   run: |
    #     sudo grype docker:docker:darkwizard242/ansible:${{ matrix.TAG_NAME }}

    - name: Archive and upload Dockerfile
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.TAG_NAME }}_image_artifacts
        path: ${{ matrix.TAG_NAME }}/
