name: docker-ansible-master-build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 7
      matrix:
        TAG_NAME: [ubuntu-20.04, ubuntu-18.04, rockylinux-8, centos-7, debian-buster]

    steps:
    - uses: actions/checkout@v2

    - name: Install Grype for Vulnerability Scanning of Docker images.
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: DockerHub auth
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}

    - name: Build docker image tag ${{ matrix.TAG_NAME }} & push to dockerhub
      uses: docker/build-push-action@v2
      with:
        file: ${{matrix.TAG_NAME}}/Dockerfile
        pull: true
        push: true
        tags: darkwizard242/ansible:${{ matrix.TAG_NAME }}

    - name: Run Grype for Vulnerability Scanning of image
      run: |
        grype darkwizard242/ansible:${{ matrix.TAG_NAME }}

    - name: Archive and upload Dockerfile
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.TAG_NAME }}_image_artifacts
        path: ${{ matrix.TAG_NAME }}/
