name: docker-automated-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 6
      matrix:
        TAG_NAME: [ubuntu-18.04, ubuntu-16.04, centos-7, debian-buster, debian-stretch, debian-jessie]

    steps:
    - uses: actions/checkout@v1
    - name: Install Trivy for Vulnerability Scanning of Docker images.
      run: |
        curl -fsSL https://raw.githubusercontent.com/darkwizard242/devopsubuntu1804/v1.0/packer-build/mods/27-trivy.sh | sudo bash -s -- install
    - name: Build docker image
      env:
        DOCKER_HUB_USER: ${{ secrets.USER }}
        DOCKER_HUB_PASS: ${{ secrets.PASS }}
      run: |
        echo -e "\nLogging into Docker Hub...\n"
        echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
        echo -e "\nBuilding image for:\tdarkwizard242/ansible:${{ matrix.TAG_NAME }}\n"
        docker build . -f ${{matrix.TAG_NAME}}/Dockerfile --tag darkwizard242/ansible:${{ matrix.TAG_NAME }}
    - name: Run Trivy for Vulnerability Scanning of image
      run: |
        export TRIVY_TIMEOUT_SEC=360s
        trivy -severity HIGH,CRITICAL,MEDIUM,LOW darkwizard242/ansible:${{ matrix.TAG_NAME }}
    - name: Deploy newly built image to DockerHub
      run: |
        echo -e "\nPushing build image of:\tdarkwizard242/ansible:${{ matrix.TAG_NAME }}\tto Dockerhub..\n"
        docker push darkwizard242/ansible:${{ matrix.TAG_NAME }}
        echo -e "\nNew image for:\tdarkwizard242/ansible:${{ matrix.TAG_NAME }} has now been pushed to Dockerhub  !!!"
    - name: Archive and upload Dockerfile
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.TAG_NAME }}_image_artifacts
        path: ${{ matrix.TAG_NAME }}/
