name: Docker Image CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feature_*

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 6
      matrix:
        TAG_NAME: [ubuntu-18.04, ubuntu-16.04, centos-7, debian-buster, debian-stretch, debian-jessie]

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image for ansible:${{matrix.TAG_NAME}}
      run: docker build . --file ${{matrix.TAG_NAME}}/Dockerfile --tag ansible:${{matrix.TAG_NAME}}
