name: docker-ansible-automated-build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 7
      matrix:
        TAG_NAME: [ubuntu-18.04, ubuntu-16.04, centos-8, centos-7, debian-buster, debian-stretch, debian-jessie]

    steps:
    - uses: actions/checkout@v1
    - name: Install Trivy for Vulnerability Scanning of Docker images.
      run: |
        curl -fsSL https://raw.githubusercontent.com/darkwizard242/devopsubuntu1804/v1.0/packer-build/mods/27-trivy.sh | sudo bash -s -- install
    - name: Build docker image tag ${{ matrix.TAG_NAME }} & push to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        dockerfile: ${{matrix.TAG_NAME}}/Dockerfile
        repository: darkwizard242/ansible
        tags: ${{ matrix.TAG_NAME }}
    - name: Run Trivy for Vulnerability Scanning of image
      run: |
        export TRIVY_TIMEOUT_SEC=360s
        trivy --severity HIGH,CRITICAL,MEDIUM,LOW darkwizard242/ansible:${{ matrix.TAG_NAME }}
    - name: Archive and upload Dockerfile
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.TAG_NAME }}_image_artifacts
        path: ${{ matrix.TAG_NAME }}/
